MODEL:
  META_ARCHITECTURE: "AdaptiveTeacherGeneralizedRCNN"
  # WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  BACKBONE:
    NAME: "build_vgg_backbone"
  ROI_HEADS:
    IN_FEATURES: ["vgg4"]
    NAME: "AdaptiveTeacherStandardROIHeads"
    NUM_CLASSES: 8
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
  RPN:
    IN_FEATURES: ["vgg4"]
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
INPUT:
  MIN_SIZE_TRAIN: (600,)
  MAX_SIZE_TRAIN: 1600
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 1600
DATASETS:
  TRAIN: ("cityscapes_instancesonly_train",)
  TRAIN_TARGET: ("cityscapes_instancesonly_foggy_train_foggy_beta_0.02",)  # inductive setting
  TEST: ("cityscapes_instancesonly_val", "cityscapes_instancesonly_foggy_val_foggy_beta_0.02")  # inductive setting
SOLVER:
  STEPS: (60000,)
  FACTOR_LIST: (1,)
  MAX_ITER: 100000
  WARMUP_ITERS: 1000
  CHECKPOINT_PERIOD: 1000
  IMS_PER_BATCH: 1
  IMS_PER_BATCH_TARGET: 1
  BASE_LR: 0.04
TEST:
  EVAL_PERIOD: 1000
  IMS_PER_BATCH: 1
DATALOADER:
  SUP_PERCENT: 100.0
SEMISUPNET:
  BBOX_THRESHOLD: 0.8
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 10000
  EMA_KEEP_RATE: 0.999696
  UNSUP_LOSS_WEIGHT: 1.0
  SUP_LOSS_WEIGHT: 1.0
  DIS_TYPE: "vgg4" #["concate","p2","multi"]
  INS_DC: False
VIS_PERIOD: 1000
VERSION: 2
SEED: 42
TRAINER: "adaptive_teacher"
