MODEL:
  META_ARCHITECTURE: "SourceFreeAdaptiveTeacherGeneralizedRCNN"
  WEIGHTS: /cluster/scratch/username/cityscape_detectron_output/r_101_c4_cs_adabn/adabn.pth
  # WEIGHTS: /cluster/scratch/username/cityscape_detectron_output/r_101_c4_cs_source/model_0025999.pth
  MASK_ON: False
  RESNETS:
    DEPTH: 101
    NORM: BN
  ROI_HEADS:
    NAME: "SourceFreeAdaptiveTeacherStandardROIHeads"
    NUM_CLASSES: 8
    BATCH_SIZE_PER_IMAGE: 256
    # SCORE_THRESH_TEST: 45
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    FC_DIM: 2048
    POOLER_RESOLUTION: 7
  ANCHOR_GENERATOR:
    SIZES: [ [ 64, 128, 256, 512 ] ]
  RPN:
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000
    BATCH_SIZE_PER_IMAGE: 256
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
INPUT:
  MIN_SIZE_TRAIN: [600]
  MIN_SIZE_TEST: 600
OUTPUT_DIR: /cluster/scratch/username/cityscape_detectron_output/r_101_c4_cs_adaptive_teacher_source_free_single_wq_adabn
DATASETS:
  TRAIN: ("cityscapes_instancesonly_foggy_train_foggy_beta_0.02_adabn",)
  TRAIN_TARGET: ("cityscapes_instancesonly_foggy_train_foggy_beta_0.02",)
  TEST: ("cityscapes_instancesonly_val", "cityscapes_instancesonly_foggy_val_foggy_beta_0.02",)
SOLVER:
  STEPS: (60000, 80000, 90000, 360000)
  # FACTOR_LIST: (1, 1, 1, 1, 1)
  MAX_ITER: 50000
  WARMUP_ITERS: 1000
  CHECKPOINT_PERIOD: 5000
  IMS_PER_BATCH: 1
  IMS_PER_BATCH_TARGET: 1
  # BASE_LR: 0.025
  BASE_LR: 0.00025
TEST:
  EVAL_PERIOD: 10
  IMS_PER_BATCH: 1
DATALOADER:
  SUP_PERCENT: 100.0
SEMISUPNET:
  BBOX_THRESHOLD: 0.8
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 2000 # 20000
  EMA_KEEP_RATE: 0.9996
  UNSUP_LOSS_WEIGHT: 1.0
  SUP_LOSS_WEIGHT: 1.0
  # DIS_TYPE: "res4" #["concate","p2","multi"]
  DIS_TYPE: "res4"
  INS_DC: True
WEAK_STRONG_AUGMENT: True
# ENHANCE: False
VIS_PERIOD: 100
VERSION: 2
SEED: 42
ADAPTIVE_THRESHOLD:
  ENABLED: False
  WARM_UP: 100
  RESERVE: 500
TRAINER: "source_free_adaptive_teacher_single"
