MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  # WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  WEIGHTS: /cluster/scratch/username/cityscape_detectron_output/r_101_c4_cs_source/model_0025999.pth
  MASK_ON: False
  RESNETS:
    DEPTH: 101
    NORM: BN
  ROI_HEADS:
    NAME: "StandardROIHeads"
    NUM_CLASSES: 8
    BATCH_SIZE_PER_IMAGE: 256
    # SCORE_THRESH_TEST: 45
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    FC_DIM: 2048
    POOLER_RESOLUTION: 7
  ANCHOR_GENERATOR:
    SIZES: [ [ 64, 128, 256, 512 ] ]
  RPN:
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000
    BATCH_SIZE_PER_IMAGE: 256
  PROPOSAL_GENERATOR:
    NAME: "RPN"
INPUT:
  MIN_SIZE_TRAIN: [600]
  MIN_SIZE_TEST: 600
OUTPUT_DIR: /cluster/scratch/username/cityscape_detectron_output/r_101_c4_cs_adabn
DATASETS:
  TRAIN: ("cityscapes_instancesonly_foggy_train_foggy_beta_0.02",)
  TRAIN_TARGET: ("cityscapes_instancesonly_foggy_train_foggy_beta_0.02",)
  TEST: ("cityscapes_instancesonly_val", "cityscapes_instancesonly_foggy_val_foggy_beta_0.02")
DATALOADER:
  NUM_WORKERS: 1
SOLVER:
  STEPS: (60000, 80000, 90000)
  MAX_ITER: 40000
  WARMUP_ITERS: 1000
  CHECKPOINT_PERIOD: 5000
  IMS_PER_BATCH: 1
  BASE_LR: 0.04
TEST:
  EVAL_PERIOD: 5000
  IMS_PER_BATCH: 1
VIS_PERIOD: 5000
VERSION: 2
SEED: 42
TRAINER: "base"
